---
- hosts: nodes
  vars:
    HOSTNAME: devbox
    USER: pl
    HOME: "/home/{{USER}}"
    DIR_BIN: "{{ HOME }}/bin"
    DOTFILES_REPO: git@github.com:parallellink/dotfiles.git
  become: true
  become_user: root
  roles:
    - common
    - dotfiles
    - golang