########
# sudo #
########
- name: create sudo file
  become: true
  become_user: root
  template:
    src: "{{ item }}-nopasswd.j2"
    dest: /etc/sudoers.d/{{ item }}-nopasswd
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ USER }}"

######################
# create directories #
######################
- name: create my directories
  file: path="{{ item }}" owner={{ USER }} group={{ USER }} mode="0755" state=directory
  with_items:
    - "{{ DIR_APP }}"
    - "{{ DIR_BIN }}"
    - "{{ DIR_LOG }}"
    - "{{ DIR_SRC }}"

############
# dotfiles #
############
- name: deploy dotfiles
  git: repo="{{ URL_DOTFILES }}" dest="{{ DIR_DOTFILES }}" key_file="$HOME/.ssh/id_rsa" accept_hostkey=yes

- name: gitconfig.local
  copy:
    src=gitconfig.local dest="$HOME/.gitconfig.local" mode="0600"

- name: deploy gitconfig
  file: src="{{ DIR_DOTFILES }}/git/gitconfig" dest="$HOME/.gitconfig" state=link

- name: deploy tmux conf
  file: src="{{ DIR_DOTFILES }}/tmux/tmux.conf" dest="$HOME/.tmux.conf" state=link

################
# emacs config #
################

- file: path="$HOME/.emacs" state=absent

- name: emacs.d
  file: src="{{ DIR_DOTFILES }}/emacs.d" dest="$HOME/.emacs.d" state=link

- file: path="$HOME/.emacs.d/custom.el" state=touch

##############
# zsh config #
##############
- name: oh my zsh
  git: repo="git://github.com/robbyrussell/oh-my-zsh.git" dest="$HOME/.oh-my-zsh"

- name: delete default zshrc
  file: path="$HOME/.zshrc" state=absent

- name: .zshrc
  file: src="{{ DIR_DOTFILES }}/oh-my-zsh/zshrc" dest="$HOME/.zshrc" state=link

- name: .shrc.d
  file: path="{{ DIR_SHRC }}" state=directory

################
# emacs config #
################
- name: emacs server scripts
  copy: src="bin/{{ item }}" dest="{{ DIR_BIN }}/{{ item }}" mode="0700"
  with_items:
    - emacs-server-start
    - emacs-server-stop

- name: emacs shell script
  copy: src="emacs.sh" dest="{{ DIR_SHRC }}/emacs.sh" mode="0700"
