- name: install stack dependencies
  dnf: name="{{ item }}" state=latest
  with_items:
    - perl
    - make
    - automake
    - gcc
    - gmp-devel
    - libffi
    - zlib
    - xz
    - tar
    - git
    - gnupg
    - ncurses-compat-libs

- name: create zshrc.d/haskell.sh            
  copy:
    src: haskell.sh
    dest: "{{ ZSHRCD }}/haskell.sh"
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: "0700"            

- stat: path=/usr/local/bin/stack
  register: haskell_stack_exists

- name: install stack
  become: true
  become_user: "{{ USER }}"
  raw: "curl -sSL https://get.haskellstack.org | sh"
  when: haskell_stack_exists.stat.exists == False

- name: stack setup
  become: true
  become_user: "{{ USER }}"
  raw: "/usr/local/bin/stack setup"
  when: haskell_stack_exists.stat.exists == False